name: "Release Helper"
description: "Automates some of the release process"
branding:
  icon: file-text
  color: purple

inputs:
  operation:
    description: |
      What you want the action to do. Must be one of these choices:
      Update CHANGELOG? "prepare for release" (or "prepare")
      Generate release notes? "github release notes" (or "github")
    required: true
  version_script_path:
    description: |
      Optional file location for an versions-updating helper file. The file should contain a list of file paths 
      and strings that need updating with the new version number. "X" out the version numbers.
      Only relevant for operation "prepare for release". See README for example.
    required: false

outputs:
  release-notes:
    description: |
      The PR description, plus commits sorted into "New features", "Bug fixes" or "Under the hood". 
      Otherwise "Changes" if issue labels are missing.
    value: ${{ steps.changelog-creator.outputs.notes }}

runs:
  using: "composite"
  steps:
    - id: changelog-creator
      shell: bash
      run: |
        bundle exec ruby run.rb 2>&1 | tee output.txt
        echo ::set-output name=notes::$(tail -n 1 output.txt)
      env:
        INPUT_OPERATION: ${{ inputs.operation }}
        INPUT_BASE_BRANCH: ${{ inputs.base_branch }}
        INPUT_VERSION_SCRIPT_PATH: ${{ inputs.version_script_path }}
