name: "Generate changelog"
description: "Creates a changelog out of the new commits"
branding:
  icon: filter
  color: red

outputs:
  release-notes:
    description: |
      The PR description, plus commits sorted into "New features", "Bug fixes" or "Under the hood". 
      Otherwise "Miscellaneous" if "type:" issue labels are missing.
    value: ${{ steps.changelog-creator.outputs.notes }}

runs:
  using: "composite"
  steps:
    - id: changelog-creator
      run: |
        bundle exec ruby run.rb 2>&1 | tee output.txt
        echo ::set-output name=notes::$(tail -n 1 output.txt)
      shell: bash
