name: "Generate changelog"
description: "Creates a changelog out of the new commits"
branding:
  icon: filter
  color: red

outputs:
  fancylog:
    description: |
      Commits sorted into "New features", "Bug fixes" or "Under the hood". 
      Otherwise "Miscellaneous" if "type:" issue labels are missing.
    value: ${{ steps.changelog-creator.outputs.greeting }}

runs:
  using: "composite"
  steps:
    - id: changelog-creator
      run: |
        bundle exec ruby run.rb
        echo "::set-output name=greeting::$(echo $GREETING)"
      shell: bash
