name: "Release Helper"
description: "Automates some of the release process"
branding:
  icon: file-text
  color: purple

inputs:
  operation:
    description: |
      What you want the action to do. 
      Update CHANGELOG? "prepare for release" (or "prepare")
      Generate release notes? "github release notes" (or "github")
    required: true
  base_branch:
    description: |
      Ignoring YAGNI and just adding this in now. Doesn't do anything currently.
      Name of the base branch, if not main/master. The branch that you'll release from.
    required: false
  version_script_path:
    description: |
      Ignoring YAGNI and just adding this in now. Doesn't do anything currently.
      File location for an auto-versioning helper file. The file should contain a list of file paths
      that need updating with the new version number. Haven't decided exactly what it should look
      like yet. Only relevant for operation "prepare for release".
    required: false
  slack_template_path:
    description: |
      Ignoring YAGNI and just adding this in now. Doesn't do anything currently.
      File location for a Slack release announcement template. 
      Only relevant for operation "slack release notes".
    required: false
  discourse_template_path:
    description: |
      Ignoring YAGNI and just adding this in now. Doesn't do anything currently.
      File location for a Discourse release announcement template. 
      Only relevant for operation "discourse release notes".
    required: false
  blog_post_url:
    description: |
      Ignoring YAGNI and just adding this in now. Doesn't do anything currently.
      The URL for the published blog post about the release. 
      Only relevant for the release notes operations.
    required: false

outputs:
  release-notes:
    description: |
      The PR description, plus commits sorted into "New features", "Bug fixes" or "Under the hood". 
      Otherwise "Changes" if issue labels are missing.
    value: ${{ steps.changelog-creator.outputs.notes }}

runs:
  using: "composite"
  steps:
    - id: changelog-creator
      shell: bash
      run: |
        bundle exec ruby run.rb 2>&1 | tee output.txt
        echo ::set-output name=notes::$(tail -n 1 output.txt)
      env:
        INPUT_OPERATION: { { inputs.operation } }
        INPUT_BASE_BRANCH: { { inputs.base_branch } }
        INPUT_VERSION_SCRIPT_PATH: { { inputs.version_script_path } }
        INPUT_SLACK_TEMPLATE_PATH: { { inputs.slack_template_path } }
        INPUT_DISCOURSE_TEMPLATE_PATH: { { inputs.discourse_template_path } }
        INPUT_BLOG_POST_URL: { { inputs.blog_post_url } }
