name: "Update CHANGELOG"

on: [push, pull_request]

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    # if: github.event_name == 'pull_request'
    outputs:
      release-notes: ${{ steps.release-notes.outputs.release-notes }}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: mscwilson/changelog-creator

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run ruby script
        id: release-notes
        uses: mscwilson/changelog-creator@main
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print decoded output?!
        env:
          DECODED-NOTES: ${{ steps.release-notes.outputs.release-notes }} | base64 --decode
        run: echo $DECODED-NOTES
