name: test

on: [create, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        id: test
        uses: mscwilson/changelog-test/issue_labels@v1.1
        with:
          number: ${ GITHUB_REF }
