name: "Prepare for release"

on: [pull_request]

permissions:
  contents: write

jobs:
  prepare-for-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    outputs:
      release-notes: ${{ steps.release-notes.outputs.release-notes }}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: mscwilson/changelog-creator

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Update version strings and CHANGELOG
        id: release-notes
        uses: mscwilson/changelog-creator@main
        with:
          operation: "prepare"
          version_script_path: ".github/workflows/version_locations.json"
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
