name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.1"
          bundler-cache: true # runs ‘bundle install’ and caches installed gems automatically

      - name: Run tests
        run: bundle exec rspec

      - name: Run Rubocop with autocorrect
        run: bundle exec rubocop -a
